repos:
    -   repo: https://github.com/psf/black-pre-commit-mirror
        rev: 23.12.1
        hooks:
        - id: black
          language_version: python3.10

    -   repo: https://github.com/PyCQA/flake8
        rev: 7.0.0
        hooks:
        -   id: flake8

    -   repo: https://github.com/pypa/pip-audit
        rev: v2.6.3
        hooks:
        -   id: pip-audit
            args: ["-r", "requirements.txt"]

    -   repo: https://github.com/pre-commit/mirrors-eslint
        rev: v8.56.0 
        hooks:
        -   id: eslint
