repos:
    -   repo: https://github.com/PyCQA/flake8
        rev: 7.0.0
        hooks:
        -   id: flake8
    -   repo: https://github.com/pypa/pip-audit
        rev: v2.6.3
        hooks:
        -   id: pip-audit
            args: ["-r", "requirements.txt"]
    -   repo: https://github.com/pre-commit/mirrors-eslint
        rev: v8.56.0 
        hooks:
        -   id: eslint
